django_react/django_react/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reactive/', include('reactive.urls', namespace='reactive')),
]

django_react/reactive/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^api/$', views.api, name='api'),
	url(r'^kanban/$', views.kanban, name='kanban')
]

django_react/reactive/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Note(models.Model):
	label = models.CharField(max_length=255)

	def __unicode__(self):
		return self.label

django_react/reactive/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers
import json
from models import Note
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
	return render(request, 'include.html')

@csrf_exempt
def api(request):
	if request.method == 'POST':
		Note.objects.create(label=request.POST.get('text'))

	data = serializers.serialize('json', Note.objects.all())
	return JsonResponse(json.loads(data), safe=False)

def kanban(request):
	return render(request, 'kanban.html')

django_react/reactive/templates/include.html
{% extends 'index.html' %}
{% load static %}


{% block react %}
<script type="text/babel">

var CommentBox = React.createClass({

	loadCommentsFromServer: function() {
		$.ajax({
			url: this.props.url,
			dataType: 'json',
			cache: false,
			success: function(data){
				this.setState({data: data});
			}.bind(this),
			error: function(xhr, status, err){
				console.error(this.props.url, status, err.toString());
			}.bind(this)
		});
	},

	getInitialState: function() {
		return {data: []};
	},

	componentDidMount: function() {
		this.loadCommentsFromServer();
		setInterval(this.loadCommentsFromServer, this.props.pollInterval)
	},

	handleCommentSubmit: function(comment) {
		$.ajax({
			url: this.props.url,
			dataType: 'json',
			type: 'POST',
			data: comment,
			success: function(data){
				this.setState({data:data});
			}.bind(this),
			error: function(xhr, status, err){
				console.error(this.props.url, status, err.toString());
			}.bind(this)
		});
	},

	render: function() {
		return (
			<div className='commentBox'>
				<h1>Comments</h1>
				<CommentList data={this.state.data}/>
				<CommentForm onCommentSubmit={this.handleCommentSubmit} />
			</div>
		);
	}
});

var CommentList = React.createClass({
	render: function() {

		var commentNodes = this.props.data.map(function(comment){
			return (
				<Comment author={comment.fields.label} key={comment.fields.label}>
					{comment.pk}
				</Comment>
			);
		});

		return (
			<div className='commentList'>
				{commentNodes}
			</div>
		);
	}
});

var CommentForm = React.createClass({

	getInitialState: function() {
		return {author: '', text: ''};
	},
	handleAuthorChange: function(e){
		this.setState({author: e.target.value});
	},
	handleTextChange: function(e){
		this.setState({text: e.target.value});
	},
	handleSumbit: function(e){
		e.preventDefault();
		var author = this.state.author.trim();
		var text = this.state.text.trim();
		if (!text || !author) {
			return;
		}
		this.props.onCommentSubmit({author: author, text: text})
		this.setState({author:'', text:''})
	},

	render: function() {
		return (
			<form className='commentForm' onSubmit={this.handleSumbit}>
				<input type='text' 
				placeholder='your name' 
				value={this.state.author} 
				onChange={this.handleAuthorChange} />

				<input type='text' 
				placeholder='say something' 
				value={this.state.text}
				onChange={this.handleTextChange} />
				<input type='submit' value='Post' />
			</form>
		);
	}
});

var Comment = React.createClass({
	render: function() {
		return (
			<div className='comment'>
				<h2 className='commentAuthor'>
					{this.props.author}
				</h2>
				{this.props.children}
			</div>
		);
	}
});


ReactDOM.render(
	<CommentBox url="{% url 'reactive:api' %}" pollInterval={2000} />,
	document.getElementById('content')
);


</script>
{% endblock %}

django_react/reactive/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django React</title>
    <link rel="stylesheet" href="{% static 'django_react/bootstrap-theme.css.map' %}" />
    <link rel="stylesheet" href="{% static 'django_react/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'django_react/bootstrap.css.map' %}" />
    <link rel="stylesheet" href="{% static 'django_react/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'django_react/soulstyles.css' %}" />
    <link rel="stylesheet" href="{% static 'django_react/theme.css' %}" />
    <link rel="stylesheet" href="{% static 'django_react/fa/css/font-awesome.css' %}" />
    <script src="https://unpkg.com/react@15.3.0/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@15.3.0/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-core@5.8.38/browser.min.js"></script>
    <script src="https://unpkg.com/jquery@3.1.0/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/remarkable@1.6.2/dist/remarkable.min.js"></script>
  </head>
  <body>
    <div id="content" class='container-fluid'></div>

    {% block react %}
    <!-- REQUIRE:
    <script type="text/babel">
      
    </script>-->
    {% endblock %}

  </body>
</html>

django_react/reactive/templates/kanban.html
{% extends 'index.html' %}
{% load static %}


{% block react %}
<style>
.card input{
	margin: 2px;
}
</style>

<script type="text/babel">

var Board = React.createClass({
	getInitialState: function(){
		return {cols: '', name: ''}
	},
	componentDidMount: function() {
		this.setState({cols: this.props.cols, name: this.props.name})
	},

	handleAddColumn: function() {
		if (this.state.cols + 1 > 6){ //magic number to cap at six columns
			return;
		} else
		this.setState({cols: this.state.cols + 1})
	},
	handleSubtractColumn: function() { //TODO: remove this and replace with a column-specific "Destroy" method
		if (this.state.cols - 1 == 0) {
			this.setState({cols: 1})
		} else
		this.setState({cols: this.state.cols -1})
	},

	handleNameChange: function(e) {
		this.setState({name: e.target.value});
	},

	toggleEditField: function(e) {
		$("#editBoardName").toggle();
	},

	render: function() {
		//use verbatim here for style mapping so django doesn't try to interpret the tag
		return (
			<div className='board jumbotron'>
				<h3>{this.state.name} <i className='fa fa-pencil' onClick={this.toggleEditField}/></h3>
				{% verbatim %}
				<input type='text' id='editBoardName' style={{display: 'none'}} value={this.state.name} onChange={this.handleNameChange}/>
				{% endverbatim %}
				<hr />
				<a href="#" onClick={this.handleAddColumn}>add col</a> | 
				<a href="#" onClick={this.handleSubtractColumn}> sub col</a>
				<hr />
				<div className='row'>
					{Array.from({length: this.state.cols}, (x,y) => <Column key={y} maxCards={5} />)}
				</div>
			</div>
		);
	}
});


var Column = React.createClass({
	getInitialState: function() {
		return {maxCards: '', currentCards: '', name: ''}
	},
	componentDidMount: function() {
		this.setState({maxCards: this.props.maxCards, currentCards: 0, name: 'Default Column'})
	},

	handleAddCard: function(){
		if (this.state.currentCards + 1 > this.state.maxCards){
			return;
		} else
		this.setState({currentCards: this.state.currentCards+1})
	},

	render: function() {
		//again use verbatim to prevent django from messing with style mapping
		return (
			<div className='column col-sm-4 col-md-4 col-lg-2'>
				<i className='fa fa-pencil' />
				<p>{this.state.name}</p>
				<p>Max Cards: {this.state.maxCards}</p>
				<i className='fa fa-plus' onClick={this.handleAddCard}> Card </i>
				{Array.from({length: this.state.currentCards}, (x,y) => <Card key={y} /> )}
			</div>
		);
	}
});

var Card = React.createClass({
	render: function() {
		return (
			<div className='card'>
				<textarea placeholder='placeholder' />
			</div>
		);
	}
});

ReactDOM.render(
	<Board cols={3} name={"Default Board"}/>,
	document.getElementById('content')
);


</script>
{% endblock %}